spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

discord.bot.token=${DISCORD_BOT_TOKEN}
discord.bot.developer.id=${DISCORD_DEVELOPER_ID:278957461120090113}

server.port=${PORT:8080}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}